// Auto-generated by Question Builder – Hindi/Unicode safe
// Encoding: UTF-8
const questions = {
    "1. The Alphabet": {
        "short": [
            {
                "instruction": "Look at the first letter of each word in the box. Write the word in the correct column.",
                "items": [
                    {
                        "question": "<img src='img/ch-1-1.png'>",
                        "answer": "<img src='img/ch-1-1-ans.png'>"
                    }
                ]
            },
            {
                "instruction": "Read the names of vegetables in the column. Write the letters in the words in the correct columns.",
                "items": [
                    {
                        "question": "<img src='img/ch-1-6.png'>",
                        "answer": "<img src='img/ch-1-6-ans.png'>"
                    }
                ]
            }
        ],
        "picturebased": [
            {
                "instruction": "Join the dots. Colour the toys. Write their names.",
                "items": [
                    {
                        "question": "<img src='img/ch-1-2.png'> <br> What is common between the toys?<br>Their names begin with the same ________ .",
                        "answer": "1. Doll 2. Duck<br> Their names begin with the same letter D."
                    }
                ]
            },
            {
                "instruction": "The letters in jigsaw A are not in alphabetical order. Write the letters in alphabetical order in B.",
                "items": [
                    {
                        "question": "<img src='img/ch-1-4.png'>",
                        "answer": "A, E, F, H, L, M, P, Q, R, W, Y, Z"
                    }
                ]
            },
            {
                "instruction": "Write the names of the body parts in the correct blanks.",
                "items": [
                    {
                        "question": "<img src='img/ch-1-5-1.png'><br>Now, look at the first letter of each word and write the words in alphabetical order.<br><img src='img/ch-1-5-2.png'>",
                        "answer": "<img src='img/ch-1-5-ans.png'>"
                    }
                ]
            }
        ],
        "miscellaneous": [
            {
                "instruction": "Write the small letters next to their capital forms.",
                "items": [
                    {
                        "question": "<img src='img/ch-1-3.png'>",
                        "answer": "<img src='img/ch-1-3-ans.png'>"
                    }
                ]
            },
            {
                "instruction": "Write your name here. And circle the vowels in your name in red. Circle the consonants in your name in blue.<br> _____________________________",
                "items": [
                    {
                        "question": "",
                        "answer": "Do it Yourself."
                    }
                ]
            }
        ],
        "fillblanks": [
            {
                "instruction": "Fill in the blanks to spell the name of this fruit.",
                "items": [
                    {
                        "blank": "___ A___AYA",
                        "answer": "PAPAYA"
                    },
                    {
                        "blank": "How many times has the vowel A been used in the word? ____",
                        "answer": "3 times"
                    }
                ]
            },
            {
                "instruction": "Fill in the blanks with the correct vowels to make the names of animals. The pictures will help you.",
                "items": [
                    {
                        "blank": "<img src='img/ch-1-7-1.png'> d__g",
                        "answer": "dog"
                    },
                    {
                        "blank": "<img src='img/ch-1-7-2.png'> c__t",
                        "answer": "cat"
                    },
                    {
                        "blank": "<img src='img/ch-1-7-3.png'> fr__g",
                        "answer": "frog"
                    },
                    {
                        "blank": "<img src='img/ch-1-7-4.png'> d__ck",
                        "answer": "duck"
                    },
                    {
                        "blank": "<img src='img/ch-1-7-5.png'> d__ __r",
                        "answer": "deer"
                    },
                    {
                        "blank": "<img src='img/ch-1-7-6.png'> f__sh",
                        "answer": "fish"
                    }
                ]
            },
            {
                "instruction": "Fill in the blanks with consonants to complete the names of the pictures. Match the words with the correct pictures.",
                "items": [
                    {
                        "blank": "<img src='img/ch-1-9.png'>",
                        "answer": "<img src='img/ch-1-9-ans.png'>"
                    }
                ]
            }
        ],
        "tick": [
            {
                "instruction": "Tick (&#10004;) the fruits whose names begin with a consonant.",
                "items": [
                    {
                        "question": "<img src='img/ch-1-8-1.png'> &emsp; ___",
                        "answer": "&#10006;"
                    },
                    {
                        "question": "<img src='img/ch-1-8-2.png'> &emsp; ___",
                        "answer": "&#10004;"
                    },
                    {
                        "question": "<img src='img/ch-1-8-3.png'> &emsp; ___",
                        "answer": "&#10004;"
                    },
                    {
                        "question": "<img src='img/ch-1-8-4.png'> &emsp; ___",
                        "answer": "&#10004;"
                    },
                    {
                        "question": "<img src='img/ch-1-8-5.png'> &emsp; ___",
                        "answer": "&#10004;"
                    },
                    {
                        "question": "<img src='img/ch-1-8-6.png'> &emsp; ___",
                        "answer": "&#10006;"
                    }
                ]
            }
        ]
    },
    "2. Sentences": {
        "matching": [
            {
                "question": "Match the columns to make sentences.",
                "options": [
                    "Column A",
                    "Column B",
                    "1. Trains",
                    "a. cycle on cycle tracks.",
                    "2. Ships",
                    "b. move on rail-tracks.",
                    "3. Cars",
                    "c. sail on water.",
                    "4. Joggers",
                    "d. are used on fields.",
                    "5. Cyclists",
                    "e. move on roads.",
                    "6. Tractors",
                    "f. jog on jogging tracks."
                ],
                "answers": [
                    "1. b. 2. c. 3. e. 4. f. 5. a. 6. d."
                ]
            }
        ],
        "fillblanks": [
            {
                "instruction": "Fill in the blanks with words from the box.",
                "items": [
                    {
                        "blank": "A __________ makes wooden tables and chairs.",
                        "answer": "carpenter"
                    },
                    {
                        "blank": "A __________ writes story books.",
                        "answer": "writer"
                    },
                    {
                        "blank": "A __________ teaches students.",
                        "answer": "teacher"
                    },
                    {
                        "blank": "An __________ paints pictures.",
                        "answer": "artist"
                    },
                    {
                        "blank": "A __________ drives a bus.",
                        "answer": "driver"
                    },
                    {
                        "blank": "A __________ looks after the sick in a hospital.",
                        "answer": "nurse"
                    }
                ]
            }
        ],
        "short": [
            {
                "instruction": "Think of any one person who works to help your family.",
                "items": [
                    {
                        "question": "For example, the cook, the driver, the gardener<br>Write the name of the person here. _______________<br>Make a sentence to tell what he/she does to help your family.<br>___________________________________________________________<br>What would you say to thank this person?<br>For example, for the driver you could say:<br>Thank you for driving me to school.<br>Thank you for bringing me back home.<br>Write your thank-you sentence here.<br>___________________________________________________________",
                        "answer": "Answers will vary."
                    }
                ]
            },
            {
                "instruction": "Choose the correct words to complete the sentences. Put a full stop at the end of each sentence.",
                "items": [
                    {
                        "question": "Spinach _________________________<br> is a leafy vegetable / is a thorny vegetable",
                        "answer": "Spinach is a leafy vegetable."
                    },
                    {
                        "question": "A ripe tomato _________________________<br> is blue / is red",
                        "answer": "A ripe tomato is red."
                    },
                    {
                        "question": "A pumpkin _________________________<br> is round in shape / is square in shape",
                        "answer": "A pumpkin is round in shape."
                    },
                    {
                        "question": "A cabbage _________________________<br> is a fruit / is a vegetable",
                        "answer": "A cabbage is a vegetable."
                    },
                    {
                        "question": "A potato _________________________<br> has many seeds / does not have any seeds",
                        "answer": "A potato does not have any seeds."
                    }
                ]
            },
            {
                "instruction": "Rewrite these sentences. Begin the first word of each sentence with a capital letter. Put a full stop at the end.",
                "items": [
                    {
                        "question": "i can jump and skip",
                        "answer": "I can jump and skip."
                    },
                    {
                        "question": "father likes to play cricket",
                        "answer": "Father likes to play cricket."
                    },
                    {
                        "question": "mother plays tennis",
                        "answer": "Mother plays tennis."
                    },
                    {
                        "question": "there are new swings in the park",
                        "answer": "There are new swings in the park."
                    },
                    {
                        "question": "there is a jogging track near the lake",
                        "answer": "There is a jogging track near the lake."
                    },
                    {
                        "question": "jai plays football in school",
                        "answer": "Jai plays football in school."
                    }
                ]
            },
            {
                "instruction": "Write Q for a question. Write S for a statement.",
                "items": [
                    {
                        "question": "Where do you live?",
                        "answer": "Q"
                    },
                    {
                        "question": "I like to read.",
                        "answer": "S"
                    },
                    {
                        "question": "Jaya sings well.",
                        "answer": "S"
                    },
                    {
                        "question": "Can you dance?",
                        "answer": "Q"
                    },
                    {
                        "question": "What is the time?",
                        "answer": "Q"
                    },
                    {
                        "question": "Baloo is reading a newspaper.",
                        "answer": "S"
                    }
                ]
            },
            {
                "instruction": "Complete the questions for the given answers. Put a question mark at the end of each question.",
                "items": [
                    {
                        "question": "Where _________________________________<br>Jai is in the garden.",
                        "answer": "Where is Jai?"
                    },
                    {
                        "question": "Have you _________________________________<br>Yes, I have finished my work.",
                        "answer": "Have you finished your work?"
                    },
                    {
                        "question": "Will _________________________________<br>Yes, I will help you.",
                        "answer": "Will you help me?"
                    },
                    {
                        "question": "When _________________________________<br>The football match is on Monday.",
                        "answer": "When is the football match?"
                    },
                    {
                        "question": "Who _________________________________<br>Team Blue won the match.",
                        "answer": "Who won the match?"
                    },
                    {
                        "question": "What _________________________________<br>The time is 6 p.m.",
                        "answer": "What is the time?"
                    }
                ]
            }
        ],
        "rewrite": [
            {
                "instruction": "Look at the picture. Rearrange the groups of words to make sentences about the picture.<br><img src='img/ch-2-1.png'>",
                "items": [
                    {
                        "question": "is / sleeping / the monkey",
                        "answer": "The monkey is sleeping."
                    },
                    {
                        "question": "is / feeding her babies / mother bird",
                        "answer": "Mother bird is feeding her babies."
                    },
                    {
                        "question": "eating a nut / is / the squirrel",
                        "answer": "The squirrel is eating a nut."
                    },
                    {
                        "question": "playing with / the boy / a dog / is",
                        "answer": "The boy is playing with a dog."
                    },
                    {
                        "question": "the girl / a book / is / reading",
                        "answer": "The girl is reading a book."
                    }
                ]
            },
            {
                "instruction": "Rewrite these questions. Begin each question with a capital letter and end it with a question mark.",
                "items": [
                    {
                        "question": "what is your name",
                        "answer": "What is your name?"
                    },
                    {
                        "question": "where do you live",
                        "answer": "Where do you live?"
                    },
                    {
                        "question": "when is your birthday",
                        "answer": "When is your birthday?"
                    },
                    {
                        "question": "what do you like to play",
                        "answer": "What do you like to play?"
                    },
                    {
                        "question": "where do you study",
                        "answer": "Where do you study?"
                    },
                    {
                        "question": "what is your favourite colour",
                        "answer": "What is your favourite colour?"
                    }
                ]
            }
        ]
    },
    "3. Nouns": {
        "matching": [
            {
                "question": "Match the columns to show what you can find where.",
                "options": [
                    "WHAT",
                    "WHERE",
                    "1. ducks",
                    "a. in a field",
                    "2. clouds",
                    "b. in the sea",
                    "3. scarecrow",
                    "c. on the road",
                    "4. ships",
                    "d. in a lake",
                    "5. traffic signal",
                    "e. in a park",
                    "6. swings",
                    "f. in the sky"
                ],
                "answers": [
                    "1. d. 2. f. 3. a. 4. b. 5. c. 6. e."
                ]
            }
        ],
        "short": [
            {
                "instruction": "Read the sentences and underline the naming words.",
                "items": [
                    {
                        "question": "The kitchen tap is leaking.",
                        "answer": "kitchen tap"
                    },
                    {
                        "question": "Call the plumber.",
                        "answer": "plumber"
                    },
                    {
                        "question": "He has gone to his village.",
                        "answer": "village"
                    },
                    {
                        "question": "I have the tools.",
                        "answer": "tools"
                    },
                    {
                        "question": "Tell father to fix it.",
                        "answer": "father"
                    },
                    {
                        "question": "We must not waste water.",
                        "answer": "water"
                    }
                ]
            },
            {
                "instruction": "Write a special name for these common naming words.",
                "items": [
                    {
                        "question": "boy __________",
                        "answer": "Rahul"
                    },
                    {
                        "question": "city __________",
                        "answer": "Mumbai"
                    },
                    {
                        "question": "pet __________",
                        "answer": "Tommy"
                    },
                    {
                        "question": "festival __________",
                        "answer": "Holi"
                    },
                    {
                        "question": "a day of the week __________",
                        "answer": "Sunday"
                    }
                ]
            },
            {
                "instruction": "Change these ONE words into MANY words.",
                "items": [
                    {
                        "question": "kite &emsp;&emsp; __________",
                        "answer": "kites"
                    },
                    {
                        "question": "tree &emsp;&emsp; __________",
                        "answer": "trees"
                    },
                    {
                        "question": "squirrel &emsp;&emsp; __________",
                        "answer": "squirrels"
                    },
                    {
                        "question": "ball &emsp;&emsp; __________",
                        "answer": "balls"
                    },
                    {
                        "question": "flower &emsp;&emsp; __________",
                        "answer": "flowers"
                    },
                    {
                        "question": "swing &emsp;&emsp; __________",
                        "answer": "swings"
                    },
                    {
                        "question": "girl &emsp;&emsp; __________",
                        "answer": "girls"
                    },
                    {
                        "question": "boy &emsp;&emsp; __________",
                        "answer": "boys"
                    }
                ]
            }
        ],
        "picturebased": [
            {
                "instruction": "In the word search, find the names of eight people and things we see in a school.<br><img src='img/ch-3-1.png'>",
                "items": [
                    {
                        "question": "Write the naming words you found in the word search.<br>1. __________&emsp;&emsp;2. __________<br>3. __________&emsp;&emsp;4. __________<br>5. __________&emsp;&emsp;6. __________<br>7. __________&emsp;&emsp;8. __________",
                        "answer": "<img src='img/ch-3-1-ans.png'><br>1. teacher 2. chair 3. book 4. boy 5. girl 6. principal 7. crayon 8. pencil"
                    }
                ]
            }
        ],
        "fillblanks": [
            {
                "instruction": "Fill in the blanks with suitable naming words.",
                "items": [
                    {
                        "blank": "I go to school in a __________.",
                        "answer": "bus"
                    },
                    {
                        "blank": "On a rainy day, I use a/an .",
                        "answer": "an umbrella"
                    },
                    {
                        "blank": "We play games in the __________.",
                        "answer": "playground"
                    },
                    {
                        "blank": "Our music teacher plays the __________.",
                        "answer": "piano"
                    },
                    {
                        "blank": "The school garden has many colourful __________.",
                        "answer": "flowers"
                    },
                    {
                        "blank": "The __________ takes care of all the plants.",
                        "answer": "gardener"
                    }
                ]
            },
            {
                "instruction": "Fill in the blanks with the correct naming words from the brackets.",
                "items": [
                    {
                        "blank": "Manisha is a __________. (boy/girl)",
                        "answer": "girl"
                    },
                    {
                        "blank": "Father has a __________ in South Market. (house/shop)",
                        "answer": "shop"
                    },
                    {
                        "blank": "Mother works in a __________. (museum/lake)",
                        "answer": "museum"
                    },
                    {
                        "blank": "My grandparents live in another __________. (city/school)",
                        "answer": "city"
                    },
                    {
                        "blank": "My __________ is in the army. (baby brother/grandfather)",
                        "answer": "grandfather"
                    },
                    {
                        "blank": "My grandmother writes __________ for children.(computers/books)",
                        "answer": "books"
                    }
                ]
            }
        ],
        "circleodd": [
            {
                "instruction": "Circle the odd one out.",
                "items": [
                    {
                        "question": "zebra &emsp; lion &emsp; this &emsp; penguin",
                        "answer": "this"
                    },
                    {
                        "question": "where &emsp; house &emsp; garden &emsp; forest",
                        "answer": "where"
                    },
                    {
                        "question": "sea &emsp; here &emsp; ocean &emsp; lake",
                        "answer": "here"
                    },
                    {
                        "question": "city &emsp; village &emsp; down &emsp; country",
                        "answer": "down"
                    },
                    {
                        "question": "park &emsp; make &emsp; bridge &emsp; school",
                        "answer": "make"
                    },
                    {
                        "question": "go &emsp; boat &emsp; train &emsp; aeroplane",
                        "answer": "go"
                    }
                ]
            }
        ],
        "miscellaneous": [
            {
                "instruction": "Read these naming words. Colour the special names red. Colour the common naming words blue.",
                "items": [
                    {
                        "question": "<img src='img/ch-3-2.png'>",
                        "answer": "Special names (colour red): Dinesh, Monday, Nagpur, Diwali, India, Taj Mahal<br>Common names (colour blue): book, girl, festival, ship, earth, library"
                    }
                ]
            }
        ],
        "long": [
            {
                "instruction": "Anu wrote this email to her grandmother. Underline the MANY words.",
                "items": [
                    {
                        "question": "Dear Amma,<br>Yesterday, Mummy and I went shopping.<br>We went to the grocer and bought six eggs and three packets of biscuits.<br>Then, we went to a big mall. It has many stores. I bought two pairs of shoes from the shoe store and two books from the bookstore. Mummy bought one bag and four shirts from another store.<br>We had so much fun!<br>I hope to see you in the Diwali holidays.<br>Love,<br>Anu<br>How many things did Anu and her mother buy in all?<br>Draw the shoes that Anu bought. Colour them in any way you like.",
                        "answer": "MANY words: eggs, packets, biscuits, stores, pairs, shoes, books, shirts<br>Total items bought: 6 eggs + 3 packets of biscuits + 2 pairs of shoes + 2 books + 1 bag + 4 shirts = 18 items"
                    }
                ]
            }
        ]
    },
    "4. Verbs": {
        "miscellaneous": [
            {
                "instruction": "Underline the naming words and circle the doing words.",
                "items": [
                    {
                        "question": "Father waters the plants.",
                        "answer": "Naming words:- Father, plants<br>Doing words:- waters"
                    },
                    {
                        "question": "Grandpa jogs every morning.",
                        "answer": "Naming words:- Grandpa<br>Doing words:- jogs"
                    },
                    {
                        "question": "Grandma bakes cakes.",
                        "answer": "Naming words:- Grandma, cakes<br>Doing words:- bakes"
                    },
                    {
                        "question": "Mother makes soft toys.",
                        "answer": "Naming words:- Mother, soft toys<br>Doing words:- makes"
                    },
                    {
                        "question": "Tina plays the piano.",
                        "answer": "Naming words:- Tina, piano<br>Doing words:- plays"
                    },
                    {
                        "question": "Blackie runs after squirrels.",
                        "answer": "Naming words:- Blackie, squirrels<br>Doing words:- runs"
                    }
                ]
            },{
                "instruction": "Write the -ing and -ed form of these action words.",
                "items": [
                    {
                        "question": "<img src='img/ch-4-4.png'>",
                        "answer": "<img src='img/ch-4-4-ans.png'>"
                    }
                ]
            },
            {
                "instruction": "Circle is, am, are in these sentences.",
                "items": [
                    {
                        "question": "I am helping Papa with the cooking.",
                        "answer": "am"
                    },
                    {
                        "question": "Tina and Billy are making a paperboat",
                        "answer": "are"
                    },
                    {
                        "question": "Grandma is working on her tablet.",
                        "answer": "is"
                    },
                    {
                        "question": "Baby Vicky is drinking milk.",
                        "answer": "is"
                    },
                    {
                        "question": "Grandpa and Blackie are playing in the garden.",
                        "answer": "are"
                    }
                ]
            },
            {
                "instruction": "Underline the correct action words.",
                "items": [
                    {
                        "question": "a. Ketan is jumping / jumped on the bed.<br>b. Ketan jumping / jumped on the bed yesterday.",
                        "answer": "a. jumping b. jumped"
                    },
                    {
                        "question": "a. Mother is worked / working on the laptop.<br>b. Mother working / worked on the laptop yesterday.",
                        "answer": "a. working b. worked"
                    },
                    {
                        "question": "a. Tina is cleaned / cleaning her cupboard.<br>b. Tina cleaning / cleaned her cupboard yesterday.",
                        "answer": "a. cleaning b. cleaned"
                    },
                    {
                        "question": "a. The gardener is planting / planted the saplings.<br>b. The gardener planting / planted the saplings yesterday.",
                        "answer": "a. planting b. planted"
                    }
                ]
            }
        ],
        "fillblanks": [
            {
                "instruction": "Fill in the blanks with the correct action words from the box.",
                "items": [
                    {
                        "blank": "Plumbers __________ taps.",
                        "answer": "repair"
                    },
                    {
                        "blank": "Bakers __________ cakes.",
                        "answer": "bake"
                    },
                    {
                        "blank": "Policewomen __________ traffic.",
                        "answer": "control"
                    },
                    {
                        "blank": "Florists __________ flowers.",
                        "answer": "sell"
                    },
                    {
                        "blank": "Doctors __________ patients.",
                        "answer": "treat"
                    },
                    {
                        "blank": "Pilots __________ aircraft.",
                        "answer": "fly"
                    },
                    {
                        "blank": "The alarm clock __________ at 6 a.m.",
                        "answer": "rings"
                    },
                    {
                        "blank": "Mother __________ me up.",
                        "answer": "wakes"
                    },
                    {
                        "blank": "I __________ breakfast at 7 a.m.",
                        "answer": "have"
                    },
                    {
                        "blank": "Grandma __________ with me to school.",
                        "answer": "walks"
                    },
                    {
                        "blank": "We __________ in the music class.",
                        "answer": "sing"
                    },
                    {
                        "blank": "We __________ games in the playground.",
                        "answer": "play"
                    }
                ]
            },
            {
                "instruction": "Imagine it is a rainy day and you are looking out of the window. Fill in the blanks with the -ing form of the correct words from the brackets.",
                "items": [
                    {
                        "blank": "It is __________. (rain/fall)",
                        "answer": "raining"
                    },
                    {
                        "blank": "My brother __________ is in the rain. (read/play)",
                        "answer": "playing"
                    },
                    {
                        "blank": "People are __________ umbrellas. (carry/push)",
                        "answer": "carrying"
                    },
                    {
                        "blank": "Tina is __________ in a puddle. (run/jump)",
                        "answer": "jumping"
                    },
                    {
                        "blank": "Car drivers are __________ the horn. (blow/roar)",
                        "answer": "blowing"
                    },
                    {
                        "blank": "Birds are __________ back to their nests. (fly/sit)",
                        "answer": "flying"
                    }
                ]
            },
            {
                "instruction": "Add -ing to the words in brackets and fill in the blanks.",
                "items": [
                    {
                        "blank": "Sunday is always a fun day for Anu and her family.<br>Grandpa is __________ the plants . <img src='img/ch-4-2-1.png'> (water)<br><img src='img/ch-4-2-2.png'> Papa is __________ in the kitchen. (cook)<br>Grandma is __________ the newspaper <img src='img/ch-4-2-3.png'>. (read)<br>Stella <img src='img/ch-4-2-4.png'> is __________ on her laptop. (work)<br>Anu is __________ a storybook <img src='img/ch-4-2-5.png'>. (read)<br>Rufus <img src='img/ch-4-2-6.png'> is __________ a bone. (chew)<br>Kitty is __________ with a ball <img src='img/ch-4-2-7.png'> . (play)",
                        "answer": "watering, cooking, reading, working, reading, chewing, playing"
                    }
                ]
            }
        ],
        "picturebased": [
            {
                "instruction": "How do the animals in the pictures move? Fill in the blanks. Then find the words in the word search.",
                "items": [
                    {
                        "question": "<img src='img/ch-4-1.png'>",
                        "answer": "<img src='img/ch-4-1-ans.png'><br>climb, crawl, swim, run, fly, hop"
                    }
                ]
            },
            {
                "instruction": "Swati is Vivek’s neighbour. She has come to meet Vivek. Vivek is looking at some pictures on his mother’s tablet. Fill in the blanks with is, am or are.",
                "items": [
                    {
                        "question": "SWATI: Hello, Vivek!<br>VIVEK: Hi! Come. I __________ looking at some family pictures. Would you like to see some pictures of our last holiday?<br>SWATI: I would love to!<br>VIVEK: See, this __________ Grandpa’s farmhouse. This __________ Grandma. She __________ feeding her dog, Bhalo.<br>SWATI: He __________ so big! Just like a bear!<br>VIVEK: This __________ their garden. These __________ mango trees. This __________ a papaya tree. There __________ pretty flowers in the garden.<br>SWATI: Let’s play with Pluto. Look, __________ he already wagging his tail.",
                        "answer": "am, is, is, is, is, is, are, is, are, is"
                    }
                ]
            }
        ]
    },
    "5. Articles": {
        "miscellaneous": [
            {
                "instruction": "Write the words in the correct columns.",
                "items": [
                    {
                        "question": "<img src='img/ch-5-1.png'>",
                        "answer": "<img src='img/ch-5-1-ans.png'>"
                    }
                ]
            },
            {
                "instruction": "Circle the correct words.",
                "items": [
                    {
                        "question": "TEACHER: Today we will talk about types of houses.<br>NEERA: My family and I live in a / an flat in Gandhi Nagar.<br>FARID: I live in a / an bungalow on Veer Street.<br>NEERA: I wish I could live in a / an igloo !<br>FARID: I think only a / an Eskimo knows how to live in a / an snow house.<br>JAI: When we go camping, we live in a / an tent .<br>JAYA: My grandparents live in a / an cottage in Shimla. It is a / an small one.<br>TEACHER: It does not matter if a / an house is big or a / an small one. It should make a / an happy home!",
                        "answer": "a, a, an, an, a, a, a, a, a, a, a"
                    }
                ]
            }
        ],
        "fillblanks": [
            {
                "instruction": "Fill in the blanks with a or an.",
                "items": [
                    {
                        "blank": "TEACHER: Are you ready for __________ outdoor sport?<br>GAURI: Are we going to have __________ race?<br>TEACHER: Yes, you will have __________ race, but it is a little different. It is __________ obstacle race. You have to jump over things that come in your way.<br>TARUN: Oh! That sounds fun.<br>NEHA: What kind of obstacles will we jump over?<br>TEACHER: I will keep __________ mat <img src='img/ch-5-2-1.png'style='height: 50px;'> , __________ box <img src='img/ch-5-2-2.png'style='height: 50px;'> and __________ umbrella <img src='img/ch-5-2-3.png'style='height: 50px;'> in your path.<br>Let’s go!",
                        "answer": "an, a, a, an, a, a, an"
                    }
                ]
            },
            {
                "instruction": "Fill in the blanks with a or an. Say the words aloud with a or an.",
                "items": [
                    {
                        "blank": "<img src='img/ch-5-4-1.png'> __________ owl &emsp; <img src='img/ch-5-4-2.png'> __________ parrot &emsp; <img src='img/ch-5-4-3.png'> __________ duck &emsp; <img src='img/ch-5-4-4.png'> __________ emu",
                        "answer": "an owl, a parrot, a duck, an emu"
                    },
                    {
                        "blank": "<img src='img/ch-5-4-5.png'> __________ ship &emsp; <img src='img/ch-5-4-6.png'> __________ engine &emsp; <img src='img/ch-5-4-7.png'> __________ car &emsp; <img src='img/ch-5-4-8.png'> __________ aeroplane",
                        "answer": "a ship, an engine, a car, an aeroplane"
                    },
                    {
                        "blank": "<img src='img/ch-5-4-9.png'> __________ otter &emsp; <img src='img/ch-5-4-10.png'> __________ fish &emsp; <img src='img/ch-5-4-11.png'> __________ turtle &emsp; <img src='img/ch-5-4-12.png'> __________ octopus",
                        "answer": "an otter, a fish, a turtle, an octopus"
                    },
                    {
                        "blank": "<img src='img/ch-5-4-13.png'> __________ pencil &emsp; <img src='img/ch-5-4-14.png'> __________ eraser &emsp; <img src='img/ch-5-4-15.png'> __________ book &emsp; <img src='img/ch-5-4-16.png'> __________ envelope",
                        "answer": "a pencil, an eraser, a book, an envelope"
                    }
                ]
            }
        ],
        "picturebased": [
            {
                "instruction": "Look at the picture. Write the names of any six things to eat that you see in the picture. Use a or an before the words.",
                "items": [
                    {
                        "question": "<img src='img/ch-5-3.png'>",
                        "answer": "Answers will vary.<br>1. a banana2. an orange3. a dosa 4. an apple5. a pear 6. an egg"
                    }
                ]
            }
        ]
    },
    "6. Pronouns": {
        "matching": [
            {
                "question": "Match the naming words with the correct pronouns.",
                "options": [
                    "<img src='img/ch-6-1.png'>"
                ],
                "answers": [
                    "1. c. 2. a. 3. c. 4. b. 5. a. 6. b. 7. d. 8. d."
                ]
            }
        ],
        "fillblanks": [
            {
                "instruction": "Fill in the blanks with the correct pronouns from the brackets.",
                "items": [
                    {
                        "blank": "Miss Mini is our music teacher. __________ teaches us to sing. (She/He)",
                        "answer": "She"
                    },
                    {
                        "blank": "Uncle Raman is a dentist. __________ says I must brush my teeth well. (It/He)",
                        "answer": "He"
                    },
                    {
                        "blank": "Aunty Anna is a pilot. __________ flies planes. (It/She)",
                        "answer": "She"
                    },
                    {
                        "blank": "Grandpa has a bookshop. __________ is near our house. (She/It)",
                        "answer": "It"
                    }
                ]
            },
            {
                "instruction": "Fill in the blanks with the correct words from the brackets.",
                "items": [
                    {
                        "blank": "Come in, Sara. __________ is my classroom. We sit and work here. (This/Those)",
                        "answer": "This"
                    },
                    {
                        "blank": "__________ are my classmates. They are happy to meet you. (Those/These)",
                        "answer": "These"
                    },
                    {
                        "blank": "__________ are the playgrounds. We play football there. (Those/These)",
                        "answer": "Those"
                    },
                    {
                        "blank": "__________ is the library. We read books there. (That/This)",
                        "answer": "That"
                    },
                    {
                        "blank": "__________ is the music room. We sing there. (This/That)",
                        "answer": "That"
                    }
                ]
            }
        ],
        "picturebased": [
            {
                "instruction": "Look at the picture story. Fill in the blanks with: she, I, me, we, us, it, they or you.",
                "items": [
                    {
                        "question": "<img src='img/ch-6-2.png'>",
                        "answer": "I, you, me, I, you, me, I, I, I, I, I, I, They, We, You, You"
                    }
                ]
            },
            {
                "instruction": "Look at the picture. Circle the correct pronouns.<br><img src='img/ch-6-3.png'>",
                "items": [
                    {
                        "question": "This / These is a hill.",
                        "answer": "This"
                    },
                    {
                        "question": "That / These are kites.",
                        "answer": "These"
                    },
                    {
                        "question": "This / These is our dog, Rufus.",
                        "answer": "This"
                    },
                    {
                        "question": "Those / This are eagles.",
                        "answer": "Those"
                    },
                    {
                        "question": "That / These is a big cloud.",
                        "answer": "That"
                    }
                ]
            }
        ],
        "miscellaneous": [
            {
                "instruction": "Write ONE if the underlined word points to one thing. Write MANY if the underlined word points to more than one thing.",
                "items": [
                    {
                        "question": "<u>Those</u> are big trees.&emsp;&emsp; ______________",
                        "answer": "MANY"
                    },
                    {
                        "question": "<u>That</u> is a clean pond.&emsp;&emsp; ______________",
                        "answer": "ONE"
                    },
                    {
                        "question": "<u>Those</u> are flower-beds.&emsp;&emsp; ______________",
                        "answer": "MANY"
                    },
                    {
                        "question": "<u>Those</u> are white ducks.&emsp;&emsp; ______________",
                        "answer": "MANY"
                    },
                    {
                        "question": "<u>Those</u> are boats for us to go across the river.&emsp;&emsp; ______________",
                        "answer": "MANY"
                    },
                    {
                        "question": "<u>That</u> is a dustbin for us to use.&emsp;&emsp; ______________",
                        "answer": "ONE"
                    }
                ]
            }
        ]
    },
    "7. Adjectives": {
        "matching": [
            {
                "question": "Match these pictures to their descriptions.",
                "options": [
                    "<img src='img/ch-7-9.png'>"
                ],
                "answers": [
                    "1. a. 2. d. 3. f. 4. e. 5. b. 6. c."
                ]
            }
        ],
        "miscellaneous": [
            {
                "instruction": "Underline the describing words in these sentences.",
                "items": [
                    {
                        "question": "Let us climb this low hill.<img src='img/ch-7-1.png'>",
                        "answer": "low"
                    },
                    {
                        "question": "The flowers are pretty.<img src='img/ch-7-2.png'>",
                        "answer": "pretty"
                    },
                    {
                        "question": "I love these tall trees.<img src='img/ch-7-3.png'>",
                        "answer": "tall"
                    },
                    {
                        "question": "Look at those colourful butterflies!<img src='img/ch-7-4.png'>",
                        "answer": "colourful"
                    },
                    {
                        "question": "Let us sit on this big rock.<img src='img/ch-7-5.png'>",
                        "answer": "big"
                    },
                    {
                        "question": "This pond looks clean.<img src='img/ch-7-6.png'>",
                        "answer": "clean"
                    }
                ]
            },
            {
                "instruction": "Underline the correct describing words for the nouns in capital letters.",
                "items": [
                    {
                        "question": "MOON &emsp;&emsp; round &emsp; white &emsp; tall",
                        "answer": "round, white"
                    },
                    {
                        "question": "RIVER &emsp;&emsp; deep &emsp; fat &emsp; long",
                        "answer": "deep, long"
                    },
                    {
                        "question": "GRASS &emsp;&emsp; green &emsp; soft &emsp; rude",
                        "answer": "green, soft"
                    },
                    {
                        "question": "CHILD &emsp;&emsp; happy &emsp; playful &emsp; thick",
                        "answer": "happy, playful"
                    },
                    {
                        "question": "HOUSE &emsp;&emsp; sad &emsp; small &emsp; beautiful",
                        "answer": "small, beautiful"
                    },
                    {
                        "question": "ROAD &emsp;&emsp; muddy &emsp; clean &emsp; funny",
                        "answer": "clean, muddy"
                    }
                ]
            }
        ],
        "picturebased": [
            {
                "instruction": "Look at the pictures. Write the opposite pairs from the box.",
                "items": [
                    {
                        "question": "<img src='img/ch-7-7-1.png'><br>Write the pairs of opposite words here.<br>1. __________ – __________<br>2. __________ – __________<br>3. __________ – __________<br>4. __________ – __________<br>5. __________ – __________<br>6. __________ – __________",
                        "answer": "1. happy – sad<br>2. thick – thin<br>3. hot – cold<br>4. strong – weak<br>5. high – low<br>6. tall – short"
                    }
                ]
            },
            {
                "instruction": "Complete the crossword with the opposites of these words.",
                "items": [
                    {
                        "question": "<img src='img/ch-7-8.png'>",
                        "answer": "Across: 3. full 4. dry 6. wide 8. clean<br>Down: 1. rude 2. old 3. rich 4. hard"
                    }
                ]
            }
        ]
    },
    "8. Prepositions": {
        "miscellaneous": [
            {
                "instruction": "Underline the place words.",
                "items": [
                    {
                        "question": "RAVI: I am tired of playing.<br>BINA: Let us sit on the bench and read a book.<br>RAVI: I left my book in the car.<br>BINA: Father has parked the car near the gate.<br>RAVI: Father is jogging on the track. I do not want to disturb him.<br>BINA: Let us just sit and watch those little rabbits hopping over the rocks!<br>RAVI: The squirrels are running up and down the tree trunk.",
                        "answer": "on, in, near, on, over, up, down"
                    }
                ]
            }
        ],
        "circleodd": [
            {
                "instruction": "Circle the correct place words.",
                "items": [
                    {
                        "question": "We store drinking water in/on a jug.",
                        "answer": "in"
                    },
                    {
                        "question": "We keep our clothes in/over the cupboard.",
                        "answer": "in"
                    },
                    {
                        "question": "We keep books on/over the bookshelf.",
                        "answer": "on"
                    },
                    {
                        "question": "We park the car on/in the garage.",
                        "answer": "in"
                    },
                    {
                        "question": "We have a bath in/near the washroom.",
                        "answer": "in"
                    }
                ]
            }
        ],
        "picturebased": [
            {
                "instruction": "Look at the pictures. Do the sentences describe the pictures correctly? Circle YES or NO.",
                "items": [
                    {
                        "question": "<img src='img/ch-8-1-1.png'><br>The book is in the table.<br>YES / NO",
                        "answer": "NO"
                    },
                    {
                        "question": "<img src='img/ch-8-1-2.png'><br>The clothes are in the cupboard.<br>YES / NO",
                        "answer": "YES"
                    },
                    {
                        "question": "<img src='img/ch-8-1-3.png'><br>The cat is on the bed.<br>YES / NO",
                        "answer": "NO"
                    },
                    {
                        "question": "<img src='img/ch-8-1-4.png'><br>The toys are in the box.<br>YES / NO",
                        "answer": "YES"
                    },
                    {
                        "question": "<img src='img/ch-8-1-5.png'><br>The school bag is on the table.<br>YES / NO",
                        "answer": "NO"
                    },
                    {
                        "question": "<img src='img/ch-8-1-6.png'><br>The laptop is on the table.<br>YES / NO",
                        "answer": "YES"
                    }
                ]
            }
        ]
    },
    "9. Conjunctions": {
        "miscellaneous": [
            {
                "instruction": "Underline the conjunctions in these sentences.",
                "items": [
                    {
                        "question": "I like to eat fruits and vegetables.",
                        "answer": "and"
                    },
                    {
                        "question": "You can have an apple or a banana for breakfast.",
                        "answer": "or"
                    },
                    {
                        "question": "Pizzas are delicious, but they are not good for health.",
                        "answer": "but"
                    },
                    {
                        "question": "Rice and chapatti give us energy.",
                        "answer": "and"
                    },
                    {
                        "question": "I like mangoes, but my brother does not like them.",
                        "answer": "but"
                    }
                ]
            }
        ],
        "fillblanks": [
            {
                "instruction": "Fill in the blanks with the correct conjunctions from the brackets.",
                "items": [
                    {
                        "blank": "FATHER: Do you want to help Amma __________ me? (but/and)<br>AVI: Yes, I do.<br>FATHER: Good! I need help to wash the car.<br>AVI: I will first make my bed __________ clean my room. Then, I will come to help you. (and/or)<br>FATHER: Oh, then I have time to send a few emails __________ tidy up the study too. (and/or)<br>AVI: After we wash the car, will you play an indoor __________ outdoor game with me? (but/or)<br>FATHER: I would love to play outdoors, __________ it is a hot day. (or/but)",
                        "answer": "1. and 2. and 3. and 4. or 5. but"
                    }
                ]
            }
        ],
        "short": [
            {
                "instruction": "A conjunction joins each of these sentences. Remove the conjunction and write two sentences in each case.",
                "items": [
                    {
                        "question": "<img src='img/ch-9-1-1.png'><br>The sky is cloudy, but it will not rain today.<br>_____________________________________________<br>_____________________________________________",
                        "answer": "The sky is cloudy. It will not rain today."
                    },
                    {
                        "question": "<img src='img/ch-9-1-2.png'><br>Sanjay and Gita like to paint.<br>_____________________________________________<br>_____________________________________________",
                        "answer": "Sanjay likes to paint. Gita likes to paint."
                    },
                    {
                        "question": "<img src='img/ch-9-1-3.png'><br>Grandma does yoga in the morning and goes for a walk in the evening.<br>_____________________________________________<br>_____________________________________________",
                        "answer": "Grandma does yoga in the morning. She goes for a walk in the evening."
                    },
                    {
                        "question": "<img src='img/ch-9-1-4.png'><br>Mani looks happy, but Sunil looks sad.<br>_____________________________________________<br>_____________________________________________",
                        "answer": "Mani looks happy. Sunil looks sad."
                    },
                    {
                        "question": "<img src='img/ch-9-1-5.png'><br>I like to play video games, but my turtle likes to read.<br>_____________________________________________<br>_____________________________________________",
                        "answer": "I like to play video games. My turtle likes to read."
                    }
                ]
            },
            {
                "instruction": "Join the sentences with <b>and</b> or<b>but</b> and rewrite them.",
                "items": [
                    {
                        "question": "<img src='img/ch-9-2-1.png'><br>Dogs are loving. They are loyal pets.<br>_____________________________________________",
                        "answer": "Dogs are loving and they are loyal pets."
                    }
                ]
            },
            {
                "instruction": "Join the sentences with and or but and rewrite them.",
                "items": [
                    {
                        "question": "<img src='img/ch-9-2-2.png'><br>An ostrich is a bird. It cannot fly.<br>_____________________________________________",
                        "answer": "An ostrich is a bird, but it cannot fly."
                    },
                    {
                        "question": "<img src='img/ch-9-2-3.png'><br>A whale swims in water. It is not a fish.<br>_____________________________________________",
                        "answer": "A whale swims in water, but it is not a fish."
                    },
                    {
                        "question": "<img src='img/ch-9-2-4.png'><br>Elephants live up to 70 years. Mayflies live for only 24 hours.<br>_____________________________________________",
                        "answer": "Elephants live up to 70 years, but mayflies live for only 24 hours."
                    }
                ]
            }
        ]
    },
    "10. Comprehension-A Vacation": {
        "tick": [
            {
                "instruction": "A VACATION<br>Ann, Fred and their parents have come to spend a few days with their friends, Mr and Mrs Guha and their son, Vicky.<br>Look at the picture carefully and answer the questions.<br><img src='img/ch-10-1.png'><br>Look at the picture again. Circle the correct words.",
                "items": [
                    {
                        "question": "Ann and Fred have their __________ vacation. (summer/winter)",
                        "answer": "summer"
                    },
                    {
                        "question": "Ann and her family had come to visit their friends in the __________. (hills/plains/desert)",
                        "answer": "hills"
                    },
                    {
                        "question": "The Guha family __________ to keep pets. (likes/does notlike)",
                        "answer": "likes"
                    },
                    {
                        "question": "It seems the two families had a __________ time together.(boring/wonderful)",
                        "answer": "wonderful"
                    }
                ]
            }
        ],
        "short": [
            {
                "instruction": "From the poem, find and write four words that rhyme with the word lay.",
                "items": [
                    {
                        "question": "",
                        "answer": "say, may, way and day"
                    }
                ]
            }
        ],
            
    },
    "10. Comprehension-Please, Thank You And Pardon Me": {
        "fillblanks": [
            {
                "instruction": "Fill in the blanks with the correct words.",
                "items": [
                    {
                        "blank": "Please is a __________ word. (polite/rude)",
                        "answer": "polite"
                    },
                    {
                        "blank": "If we do not hear what someone is saying, we should say __________. (thank you/pardon me)",
                        "answer": "pardon me"
                    },
                    {
                        "blank": "If we use polite words __________, they will become a part of our everyday words. (sometimes/many times)",
                        "answer": "many times"
                    },
                    {
                        "blank": "We should use polite words for __________. (only teachers/everyone)",
                        "answer": "everyone"
                    },
                    {
                        "blank": "The poet is speaking to a __________. (child/ an adult)",
                        "answer": "child"
                    }
                ]
            }
        ],
        "short": [
            {
                "instruction": "From the poem, find and write four words that rhyme with the word lay.",
                "items": [
                    {
                        "question": "",
                        "answer": "say, may, way and day"
                    }
                ]
            },
            {
                "instruction": "Write a polite word that is not mentioned in the poem..",
                "items": [
                    {
                        "question": "",
                        "answer": "Excuse me"
                    }
                ]
            }
        ],
            
    },
    "10. Comprehension-Blue Fairy’s Birthday Party": {
        "truefalse": [
            {
                "instruction": "Write T for true or F for false.",
                "items": [
                    {
                        "question": "Pink Fairy and Greenie were both fairies.",
                        "answer": "F"
                    },
                    {
                        "question": "The party was held under the oak tree.",
                        "answer": "T"
                    },
                    {
                        "question": "Mother Fairy gave return gifts to all the fairies and elves.",
                        "answer": "T"
                    },
                    {
                        "question": "The chocolate cake was round in shape.",
                        "answer": "F"
                    },
                    {
                        "question": "Blue Fairy liked all the gifts.",
                        "answer": "T"
                    }
                ]
            }
        ],
        "tick": [
            {
                "instruction": "Tick the correct answers.",
                "items": [
                    {
                        "question": "Two/Three/Four things on the tree made it look colourful and pretty.",
                        "answer": "Three"
                    },
                    {
                        "question": "There was a tasty square/round/iced chocolate cake.",
                        "answer": "square"
                    }
                ]
            }
        ],
        "short": [
            {
                "instruction": "Which words in the story mean the same as the following?",
                "items": [
                    {
                        "question": "made of many colours _______________________",
                        "answer": "colourful"
                    },
                    {
                        "question": "tasty _______________________",
                        "answer": "delicious"
                    },
                    {
                        "question": "liked _______________________",
                        "answer": "pretty/beautiful"
                    }
                ]
            }
        ],
            
    },
    "10. Comprehension-I’m A Little Airplane": {
        "tick": [
            {
                "instruction": "Tick the correct answers.",
                "items": [
                    {
                        "question": "Who is ‘I’ in the poem?<br>&emsp; a. airplane &emsp;&emsp; b. sky",
                        "answer": "a"
                    },
                    {
                        "question": "Can the little airplane fly?<br>&emsp; a. Yes &emsp;&emsp; b. No",
                        "answer": "a"
                    }
                ]
            }
        ],
    },
    "11. Composition": {
        "fillblanks": [
            {
                "instruction": "Complete the poem with the words given in the box.",
                "items": [
                    {
                        "blank": "FIVE LITTLE DUCKS<br>Five little ducks went out one day<br>Over the hill and far away<br>Mother Duck said, “Quack, quack, quack,”<br>But only four little ducks came back<br>One, two, __________, four<br>Four little ducks went out one day<br>Over the hill and far away<br>Mother Duck said, “ __________ ”<br>But only three little ducks __________<br>One, two, __________<br>Three little ...<br>Two little ...<br>One little duck went out one day<br>Over the hill and far away<br>__________ said, “Quack, quack, quack,”<br>But none of the five little ducks came back<br>Sad Mother Duck went out one day<br>Over the hill and far away<br>Mother Duck said, “Quack, quack, quack,”<br>And all the __________ came back.",
                        "answer": "three,  quack, quack, quack, came back, Mother duck, five little ducks"
                    }
                ]
            },
            {
                "instruction": "Complete the story in your own words.<br><img src='img/ch-11-1.png'>",
                "items": [
                    {
                        "blank": "One day a cap-seller was walking through a forest. He felt tired and wanted to __________. He __________ under a tree, and __________.<br>There were four monkeys on the __________. They jumped __________and wore __________. Then, they __________.<br>When the cap-seller woke up, he was __________. He looked around. He could not __________. Then, he looked __________. He saw __________.<br>He thought of a plan.",
                        "answer": "Do it yourself"
                    }
                ]
            }
        ]
    }
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = questions;
}
